---
title: "Untitled"
author: "Kevin Wang"
date: "07/03/2020"
output: html_document
---


# Loading 

## Packages
```{r}
library(keras)
```


## Customised functions
```{r}
# define image preprocessor for use with keras vgg19
image_preprocessor = function(image_path) {
    image = image_load(image_path, target_size = c(224,224))
    image = image_to_array(image)
    image = array_reshape(image, c(1, dim(image)))
    image = imagenet_preprocess_input(image)
    return(image)
}

#function to read in files housing all cat/dog breeds in imagenet labels
read_dog_cat_labels = function(path) {
    labs = readLines(path)
    labs = trimws(unlist(strsplit(labs, ',')))
    labs = gsub('\\s+', '_', labs)
    return(labs)
}
```


## Images
```{r}
# define image paths to classify
image_paths = list.files('keras_image_r_python/images/', recursive = TRUE, full.names = TRUE)

# preprocess images
image_list = lapply(image_paths, image_preprocessor)
```


## Model
```{r}
# load vgg19 model pretrained with imagenet
model = application_vgg19(weights = 'imagenet')
```


# Making prediction with existing model 

```{r}
# get model prediction
preds = lapply(image_list, function(i) {
    imagenet_decode_predictions(predict(model, i), top = 1)[[1]]
})

pred_df = do.call(rbind, preds)
pred_df$class_name = NULL

pred_df
```

## Adding cats/dogs labels

The model only outputs breeds of the animal, not species. 

```{r}
dog_labs = read_dog_cat_labels('keras_image_r_python/data/dog_classes.txt')
cat_labs = read_dog_cat_labels('keras_image_r_python/data/cat_classes.txt')

#create column for labeling dog breeds as dog and cat breeds as cat
pred_df$catdog = NA
pred_df$catdog[pred_df$class_description %in% dog_labs] = 'Dog'
pred_df$catdog[pred_df$class_description %in% cat_labs] = 'Cat'


#add column with image paths
pred_df$file_name = unlist(image_paths)
pred_df = pred_df[order(-pred_df$score),]
#------------------------------------------------

#####################
# print output
#####################
print(pred_df)
```

# Download a new file and make prediction
```{r}
download.file("https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12234558/Chinook-On-White-03.jpg", destfile = "tmp.jpg")

imagenet_decode_predictions(predict(model, image_preprocessor("tmp.jpg")))[[1]]
```